version: "3.8"

########## SERVICES ##########
services:
#### Nginx ####
  my-nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: my-nginx-img
    restart: always
    volumes: 
      - wordpress-volume:/var/www/wordpress
    ports:
      - 443:443
    networks:
      - my-network

#### Wordpress ####
  my-wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: my-wordpress-img
    restart: always
    volumes: 
      - wordpress-volume:/var/www/wordpress
    env_file:
      - .env
    networks:
      - my-network

#### Mariadb ####
  my-mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: my-mariadb-img
    restart: always
    volumes: 
      - mariadb-volume:/var/lib/mysql
    environment:
      - MARIADB_DB_NAME=$MARIADB_DB_NAME
      - MARIADB_ROOT=$MARIADB_ROOT
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_USER_PASSWORD=$MARIADB_USER_PASSWORD
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
    networks:
      - my-network

########## NETWORK ##########
networks: 
  my-network:
    driver: bridge

########## VOLUMES ##########
volumes:
  wordpress-volume:
      name: wordpress-volume
      driver: local
      driver_opts:
          type: none
          device: /home/jesopan-/data/wordpress
          o: bind
  mariadb-volume:
      name: mariadb-volume
      driver: local
      driver_opts:
          type: none
          device: /home/jesopan-/data/mariadb
          o: bind
