version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx-img
    restart: always
    volumes: 
      - wp-volume:/var/www/wordpress
    ports:
      - 443:443
    networks:
      - my-network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress-img
    restart: always
    volumes: 
      - wp-volume:/var/www/wordpress
    env_file:
      - .env
    networks:
      - my-network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb-img
    restart: always
    volumes: 
      - db-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my-network

networks: 
  my-network:
    driver: bridge

volumes:
  wp-volume:
      name: wp-volume
      driver: local
      driver_opts:
          type: none
          device: /home/jesopan-/data/wordpress
          o: bind
  db-volume:
      name: db-volume
      driver: local
      driver_opts:
          type: none
          device: /home/jesopan-/data/mariadb
          o: bind
