version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    volumes: 
      - wordpress-volume:/var/www/wordpress
    ports:
      - 443:443
    networks:
      - Inception
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    volumes: 
      - wordpress-volume:/var/www/wordpress
    env_file:
      - .env
    networks:
      - Inception
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    volumes: 
      - mariadb-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - Inception

networks: 
 Inception:
    driver: bridge

volumes:
  wordpress-volume:
      name: wordpress-volume
      driver: local
      driver_opts:
          type: none
          device: /home/jesopan-/data/wordpress
          o: bind
  mariadb-volume:
      name: mariadb-volume
      driver: local
      driver_opts:
          type: none
          device: /home/jesopan-/data/mariadb
          o: bind
