version: "3.8"

########## SERVICES ##########
services:
#### Nginx ####
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    volumes: 
      - wordpress-volume:/var/www/wordpress
    ports:
      - 443:443
    networks:
      - my-network
    depends_on:
      - wordpress

#### Wordpress ####
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    volumes: 
      - wordpress-volume:/var/www/wordpress
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - mariadb

#### Mariadb ####
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    volumes: 
      - mariadb-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my-network

########## NETWORK ##########
networks: 
  my-network:
    driver: bridge

########## VOLUMES ##########
volumes:
  wordpress-volume:
      name: wordpress-volume
      driver: local
      driver_opts:
          type: none
          device: /home/jesopan-/data/wordpress
          o: bind
  mariadb-volume:
      name: mariadb-volume
      driver: local
      driver_opts:
          type: none
          device: /home/jesopan-/data/mariadb
          o: bind
