version: "3"

services:
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html/wordpress
    env_file:
      - .env
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: requirements/nginx
    hostname: localhost
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always
    networks:
      - inception
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - data_base:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - inception

volumes:
  data_base:
    driver: local
    driver_opts:
      type: none
      device: /home/jesopan-/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jesopan-/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
